#include <nds.h>
#include <stdio.h>
#include <fat.h>
#include <dirent.h>
#include <unistd.h>
#include "ds_tools.h"
#include "highscore.h"
#include "Console.hxx"
#include "Cart.hxx"
#include "bgInstructions.h"
#include "bgBottom.h"

extern int bg0, bg0b,bg1b;

struct instructions_t 
{
    string gameID;
    const char *text;
};

const struct instructions_t instructions[] =
{
    {"ADVENT",    "ADVENTURE (C)1980 ATARI\n"
                  "BY WARREN ROBINETT\n"
                  " \n"
                  "GAME 1:  EASY - FIXED LAYOUT\n"
                  "GAME 2:  MEDIUM - FIXED LAYOUT\n"
                  "GAME 3:  HARD - RANDOM LAYOUT\n"
                  "L-DIFF:  A=DRAGON BITES FASTER\n"
                  " \n"
                  "THE EVIL MAGICIAN HAS STOLEN\n"
                  "THE GOLDEN CHALICE. IT'S HIDDEN\n"
                  "SOMEWHERE IN THE REALM AND YOU\n"
                  "MUST FIND IT AND RETURN IT TO\n"
                  "THE YELLOW CASTLE. BEWARE THE\n"
                  "DRAGONS AND BAT WHO LOOK TO\n"
                  "SPOIL YOUR ADVENTURE!\n"
    },
    
    {"ADTRON",    "ADVENTURES OF TRON (C)1982"
                  " \n"
                  "L-DIFF:  A=FASTER GAMEPLAY\n"
                  " \n"
                  "TRON! MUST CROSS THE I/O BEAM\n"
                  "TO ALLOW ELEVATORS TO LIFT.\n"
                  "INTERCEPT BITS ON 4 FLOORS.\n"
                   " \n"
                  "BIT ON 1ST FLOOR  100\n"
                  "BIT ON 2ND FLOOR  200\n"
                  "BIT ON 3RD FLOOR  400\n"
                  "BIT ON TOP FLOOR  800\n"
                  "BONUS LEVEL CLEAR 2,000\n"
                  " \n"
                  "PRESS UP/DN TO RIDE ELEVATORS.\n"
                  "WHEN ALL BITS ARE INTERCEPTED\n"
                  "RIDE THE I/O BEAM TO NEXT LEVEL\n"
                  " \n"
    },
    
    {"ASTERD",  "ASTEROIDS (C)1981 ATARI\n"
                "GAME 1: SLOW, EXTRA LIFE AT  5K\n"
                "GAME 2: FAST, EXTRA LIFE AT  5K\n"
                "GAME 3: SLOW, EXTRA LIFE AT 10K\n"
                "GAME 4: FAST, EXTRA LIFE AT 10K\n"
                "GAME 6: FAST, EXTRA LIFE AT 20K\n"
                "GAME 9: SLOW, SHIELDS, LIFE 5K\n"
                "GAME 10:FAST, SHIELDS, LIFE 5K\n"
                "GAME 12:FAST, SHIELDS, LIFE 10K\n"
                "GAME 14:FAST, SHIELDS, LIFE 20K\n"
                "GAME 16:FAST, SHIELDS, LIFE ---\n"
                "L-DIFF:  A=UFOS + SATELLITES\n"
                " \n"
                "SMALL ASTEROIDS   100 PTS\n"
                "MEDIUM ASTEROIDS   50 PTS\n"
                "LARGE ASTEROIDS    20 PTS\n"
                "SATELLITES        200 PTS\n"
                "UFOS             1000 PTS\n"
    },
    

    {"ATLANT",  "ATLANTIS (C)1982 IMAGIC"
                " \n"
                "DEFEND ATLANTIS! BLAST GORGONS\n"
                "BEFORE THEY DEMOLISH ATLANTIS!\n"
                " \n"
                "GAME 1: NORMAL GAME\n"
                "GAME 2: NO COMMAND POST!\n"
                "GAME 4: EASY GAME\n"
                " \n"
                "SCORING:\n"
                "LARGE GORGON       100/200 PTS\n"
                "SMALL GORGON     1000/2000 PTS\n"
                "BONUS 500 PTS FOR EACH AREA\n"
                "THAT SURVIVIES GORGON ASSAULT\n"
                "EXTRA LIFE EVERY 10,000 PTS\n"
                " \n"
    },
    
    {"BARNST",  "BARNSTORMING\n"
                "(C)1982 BY ACTIVISION\n"
                " \n"
                "BARNSTORM YOUR WAY THROUGH\n"
                "THE BARNS IN SHORTEST TIME!\n"
                "\n"
                "L-DIFF:  A=LOW BARNS\n"
                "R-DIFF:  A=MORE GEESE\n"
                " \n"
                "GAME 1: 10 BARNS FIXED COURSE\n"
                "GAME 2: 15 BARNS FIXED COURSE\n"
                "GAME 3: 15 BARNS FIXED COURSE\n"
                "GAME 4: 25 BARNS RANDOM COURSE\n"
    },
    
    {"BAZONE",  "BATTLEZONE (C)1983 ATARI\n"
                " \n"
                "GAME 1: NOVICE\n"
                "GAME 2: INTERMEDIATE\n"
                "GAME 3: ADVANCED\n"
                "SCORING\n"
                "TANK         1,000 PTS\n"
                "FIGHTER      2,000 PTS\n"
                "SUPERTANK    3,000 PTS\n"
                "SAUCER       5,000 PTS\n"
                "BONUS TANK   50K AND 100K\n"        
    },
    

    {"BEAMRI",  "BEAMRIDER (C)1984 ACTIVISION\n"
                " \n"
                "L-DIFF:  A=ADVANCED GAME\n"
                " \n"
                "WELCOME TO THE BEAM! THERE ARE\n"
                "99 SECTORS - A NEW ENEMY SHOWS\n"
                "UP FOR THE FIRST 16 SECTORS.\n"
                "15 SAUCERS MUST BE DESTROYED\n"
                "IN EACH SECTOR THEN THE SECTOR\n"
                "SENTINEL SHIP APPEARS. ONLY\n"
                "A TORPEDO WILL TAKE IT OUT.\n"
                "YELLOW REJUVENATORS=EXTRA LIFE\n"
                "WHITE AND YELLOW SHIPS ARE\n"
                "VUNERABLE TO NORMAL FIRE.\n"
                "PRESS UP TO FIRE TORPEDO (3X)\n"
                "PRESS UP TO START NEW SECTOR\n"
    },
    
    {"DODGEM",  "DODGE-EM (C)1980 ATARI\n"
                " \n"
                "L-DIFF: A=COMPUTER 2X SPEED\n"
                "R-DIFF: A=COMPUTER RAND START\n"
                " \n"
                "EACH DOT REMOVED IS 1 POINT.\n"
                "BONUS OF 8 PTS PER DOT IF\n"
                "YOU CLEAR THE ENTIRE SCREEN.\n"
    },
 
    {"DEFEND",  "DEFENDER (C)1982 ATARI\n"
                " \n"
                "GM 1: NORMAL SPEED\n"
                "GM 2: FASTER SPEED\n"
                "GM 4: SAME AS GM 1 - WAVE 3\n"
                "GM 7: SAME AS GM 1 - WAVE 5\n"
                " \n"
                "L-DIFF:  A=SLOWER DEFENDER\n"
                "POD               1000 PTS\n"
                "SWARMER            500 PTS\n"
                "BOMBER             250 PTS\n"
                "BAITER             200 PTS\n"
                "LANDER             150 PTS\n"
                "MUTANT             150 PTS\n"
                "SAVE HUMAN: 250/500/1000 PTS\n"
                "BONUS DEFENDER EVERY 10K PTS\n"
    },
    
    {"DRFIRE",  "DRAGONFIRE (C)1982 IMAGIC\n"
                "CROSS THE BRIDGE TO ENTER THE\n"
                "TREASURE ROOM AND COLLECT ALL!\n"
                "GAME 1:  START DRAGON 1\n"
                "GAME 2:  START DRAGON 3\n"
                "GAME 3:  START DRAGON 5\n"
                "GAME 4:  START DRAGON 7\n"
                "JUG          10 PTS\n"
                "LAMP         10 PTS\n"
                "GOBLET       10 PTS\n"
                "HELMET       60 PTS\n"
                "CANDELABRA   60 PTS\n"
                "CHEST       200 PTS\n"
                "HARP        200 PTS\n"
                "DIAMOND     400 PTS\n"
                "CROWN       400 PTS\n"
    },
    
    
    {"ENDURO",  "ENDURO (C)1983 ACTIVISION\n"
                " \n"
                "PASS THE REQUIRED NUMBER OF\n"
                "CARS EACH DAY TO ENDURE!\n"
                " \n"
                "PRESS BUTTON TO ACCELERATE\n"
                "PULL BACK ON JOY TO BRAKE\n"
                " \n"
                "MUST PASS 200 CARDS ON FIRST\n"
                "DAY AND 300 ON SUBSEQUENT DAYS\n"
                " \n"
                "YOUR ODOMETER IS YOUR SCORE\n"        
    },    
    
    
    {"COSCOM",  "COSMIC COMMUTER\n"
                "(C)1984 BY ACTIVISION\n"
                " \n"
                "LAND YOUR ROCKET MODULE\n"
                "GET COMMUTERS AT BUS STOPS\n"
                "BLAST OBSTACLES IN YOUR WAY\n"
                "RETURN TO ROCKET MODULE\n"
                " \n"
                "GAME 1:    NORMAL\n"
                "GAME 2:    HARDER\n"
                " \n"
                "BONUS BUS EVERY 10000 PTS\n"
    },
    
    {"MISCOM",  "MISSILE COMMAND (C)1981 ATARI\n"
                " \n"
                "SAVE ZARDON CITIES FROM ATTACK\n"
                "GM 1: SLOW TARGET,DUMB CRUISE\n"
                "GM 2: FAST TARGET,DUMB CRUISE\n"
                "GM 3: SLOW TARGET,SMART CRUISE\n"
                "GM 4: FAST TARGET,SMART CRUISE\n"
                "GM 5: SAME AS 1 - START WAVE 7\n"
                "GM 9: SAME AS 1 - START WAVE 11\n"
                " \n"
                "L-DIFF:  A=SLOWER ABMS\n"
                "IBMS                25 PTS\n"
                "CRUISE MISSILE     125 PTS\n"
                "UNUSED ABMS          5 PTS\n"
                "SAVED CITIES       100 PTS\n"
                "EVERY ODD WAVE ALL SCORING\n"
                "MULTIPLIES (2X,3X,4X,5X,ETC)\n"
                "BONUS CITY EVERY 10,000 PTS\n"
    },
    
    {"SPAINV",  "SPACE INVADERS (C)1980 ATARI\n"
                " \n"
                "GAME 1:  NORMAL GAME\n"
                "GAME 2:  MOVING SHIELDS\n"
                "GAME 3:  ZIGZAG BOMBS\n"
                "GAME 4:  MOVING SHIELDS+ZIGZAG\n"
                "GAME 5:  FAST BOMBS\n"
                "GAME 6:  MOVING SHIELDS+FAST\n"
                "GAME 7:  ZIGZAG + FAST BOMBS\n"
                "GAME 8:  MOVING+ZIGZAG+FAST\n"
                "GAME 9:  INVISIBLE INVADERS!\n"
                " \n"
                "L-DIFF:  A=FAT MISSILE BASE\n"
                " \n"            
                "THE SPACE INVADERS ARE WORTH\n"
                "5, 10, 15, 20, 25, 30 POINTS IN\n"
                "THE FIRST THROUGH SIXTH ROWS.\n"
                "ALIEN MOTHERSHIP IS WORTH 200\n"
    },
    
    {"SPACAV",  "SPACE CAVERN (C)1981 APOLLO\n"
                " \n"
                "USE YOUR PHOTON RAY TO DESTROY\n"
                "SKY ALIENS WHILE USING UP+DN\n"
                "TO HIT SHAGGY GROUND TARGETS\n"
                " \n"            
                "GAME 01: LV1 NORMAL\n"
                "GAME 03: LV1 MORE ALIENS\n"
                "GAME 07: LV1 RANDOM BLASTS\n"
                "GAME 17: LV2 NORMAL\n"
                "GAME 19: LV2 MORE ALIENS\n"
                "GAME 33: LV3 NORMAL\n"
                "GAME 35: LV3 MORE ALIENS\n"        
                "L-DIFF:  A=FRENZIED MODE\n"
                "LG ELECTROSAURUS       115 PTS\n"
                "SM ELECTROSAURUS       165 PTS\n"
                "SHAGGY MARSUPODS       200 PTS\n"
                "EXTRA LIFE EVERY 20,000 PTS\n"
    },
    
    {"SPACET",  "SPACE TREAT DELUXE\n"
                " \n"
                "GUIDE YOUR SHIP TO COLLECT\n"
                "FOOD AND BRING BACK TO SAFETY.\n"
                " \n"
                "EACH SHIP REMAINING    100 PTS\n"
                "EACH FUEL REMAINING     10 PTS\n"
                "NO LIFE LOST ON LEVEL 1000 PTS\n"
                " \n"
                "ADDITIONAL BONUS FROM 10-1000\n"
                "POINTS DEPEND ON LEVEL CLEARED\n"
                " \n"
                "THERE ARE 99 LEVELS IN ALL!\n"
    },


    
    {"STAMPE",  "STAMPEED (C)1981 ACTIVISION\n"
                " \n"
                "GAME 1:  SIDEKICK\n"
                "GAME 2:  PILGRIM\n"
                "GAME 3:  COWPOKE\n"
                "GAME 4:  WRANGLER\n"
                "GAME 5:  TOP HAND\n"
                "GAME 6:  TRAIL BOSS\n"
                "GAME 7:  RANCHER\n"
                "GAME 8:  CATTLE BARON\n"
                "L-DIFF:  A=SHORTER ROPE\n"
                " \n"            
                "BLACK ANGUS           100 PTS\n"
                "LIGHT BROWN JERSEYS    25 PTS\n"
                "MEDIUM BROWN GUERNSEYS 15 PTS\n"
                "DARK RED HEREFORDS      3 PTS\n"
    },
    
    {"YARSRE",  "YARS' REVENGE (C)1982 ATARI\n"
                " \n"
                "GAME 0:  EASY - SLOW DESTROYER\n"
                "GAME 2:  NORMAL GAME\n"
                "GAME 4:  HARD - CANNON BOUNCE\n"
                "GAME 6:  ULTIMATE YARS!\n"
                " \n"
                "L-DIFF:  A=FASTER SWIRLS\n"
                " \n"  
                "SCORING:\n"
                "CELL HIT BY MISSILE          69\n"
                "CELL DEVOURED BY YAR         69\n"
                "QOTILE DESTROYED           1000\n"
                "SWIRL DESTROYED IN PLACE   2000\n"
                "SWIRL DESTROYED IN MID-AIR 6000\n"
                " \n"            
                "AT 70,000 SWIRL TRIPLES IN FREQ\n"            
                "AT 150,000 SWIRL HEAT SEAKING\n"
    },
    
    {"FROGGR",  "FROGGER (C)1982 PARKER BROS\n"
                " \n"
                "GET FROGGIE TO THE OTHER SIDE\n"
                "BEFORE TIME RUNS OUT!\n"
                " \n"
                "GAME 1:  NORMAL GAME\n"
                "GAME 3:  FASTER GAME\n"
                "GAME 5:  FASTEST GAME\n"
                "L-DIFF: A=SIDE SCREEN DEATH\n"
                " \n"
                "FROGGER FORWARD          1 PTS\n"
                "FROGGER HOME             5 PTS\n"
                "JUMPING 5 FROGS HOME   100 PTS\n"
                "TAKING LADY FROG HOME   20 PTS\n"
                "EATING A FLY            20 PTS\n"
                "BONUS FOR SECONDS LEFT   2 PTS\n"
                "EXTRA LIFE EVERY 1000 POINTS\n"
    },

    {"OFFROG",  "OFFICIAL FROGGER\n"
                "(C) 1983 ARCADIA\n"
                " \n"
                "GET FROGGIE TO THE OTHER SIDE\n"
                "BEFORE TIME RUNS OUT!\n"
                " \n"
                "L-DIFF: A=SIDE SCREEN DEATH\n"
                " \n"
                "FROGGER FORWARD         10 PTS\n"
                "FROGGER HOME            50 PTS\n"
                "JUMPING 5 FROGS HOME  1000 PTS\n"
                "TAKING LADY FROG HOME  200 PTS\n"
                "EATING A FLY           200 PTS\n"
                "BONUS FOR SECONDS LEFT  10 PTS\n"
                "EXTRA LIFE EVERY 20000 POINTS\n"
    },
    
    {"LADBUG",  "LADY BUG (C)2006 CHAMP GAMES\n"
                " \n"
                "NOVICE:   5 LADY BUGS\n"
                "STANDARD: 4 LADY BUGS\n"
                "ADVANCED: 3 LADY BUGS\n"
                "L-DIFF: A=SLOWER LADY BUG\n"
                " \n"  
                "BLUE HEART:   2X, 3X, 5X\n"
                "YELLOW EXTRA: EXTRA LIFE\n"
                "RED SPECIAL:  BOUNTY HARVEST\n"  
                " \n"  
                "EAT FLOWER:       10 PTS\n"  
                "GET BLUE ITEM:   100 PTS\n"  
                "GET YELLOW ITEM: 300 PTS\n"  
                "GET RED ITEM:    800 PTS\n"  
                "VEGGIES ARE 500 PER LEVEL\n"  
    },
    
    
    {"OYSTRO",  "OYSTRON (C)1997 PIERO CAVINA\n"
                " \n"
                "THREE LEVELS OF DIFFICULTY:\n"
                "BEGINNER, INTERMEDIATE, ADV\n"
                "L-DIFF: A=EASIER SHIP BOUNCE\n"
                " \n"  
                "SHOOT ENEMIES AND TURN THEM\n"
                "INTO PEARLS. COLLECT PEARLS \n"
                "DROP THEM IN PEARL ZONE. \n"
                "8 PEARLS IN ROW = BOMB\n"
                " \n"  
                "SPACE OYSTER (EACH HIT): 10 PTS\n"
                "FORMATION DESTROYED:     30 PTS\n"
                "OYSTRON (WITH A BOMB): 1530 PTS\n"
                "   + (BOMBS LEFT)X100 POINTS\n"
                " \n"
                "EXTRA SHIP EVERY 4,000 POINTS\n"
    },
    
    
    {"PHASER",  "PHASER PATROL (C)1982 STARPATH\n"
                " \n"
                "L-DIFF: A=SECTOR MAP, B=COMBAT\n"
                "R-DIFF: A=HARDER GAME\n"
                "COLOR:  SHIELDS ON/OFF\n"
                " \n"  
                "DESTROY THE DRACON ARMADA!\n"
                "USE SECTOR MAP TO FIND ENEMY.\n"            
                "FIND STARBASE FOR REPAIR\n"  
                " \n"  
                "DAMAGE COLOR PER SYSTEM:\n"  
                "GREEN:  FULLY OPERATIONAL\n"  
                "YELLOW: SYSTEM DAMAGED\n"  
                "RED:    SYSTEM DESTROYED\n"  
                " \n"  
                "RANKS: HERO,ACE,PILOT,GREENHORN\n"  
    },
    
    {"PITFAL",  "PITFALL! (C)1982 ACTIVISION\n"
                " \n"  
                "YOU START WITH 2000 POINTS AND\n"
                "LOSE POINTS AS MISHAPS OCCUR.\n"
                "YOU HAVE 20 MINUTES TO COLLECT\n"
                "ALL 32 TREASURES TO FINISH.\n"
                " \n"
                "DIAMOND RING     5000 PTS\n"
                "GOLD BAR         4000 PTS\n"
                "SILVER BAR       3000 PTS\n"
                "MONEY BAG        2000 PTS\n"                                              
                " \n"
                "A PERFECT SCORE IS 114,000 PTS\n"
        },    

    {"PITFA2",  "PITFALL 2 (C)1983 ACTIVISION\n"
                " \n"  
                "FIND RHONDA, QUICKCLAW, RAT,\n"
                "DIAMOND AND ALL 28 GOLD BARS.\n"
                " \n"  
                "START WITH 4000 POINTS.\n"
                " 5,000 PTS GOLD BAR\n"
                "15,000 PTS CAVE RAT\n"
                "20,000 PTS RAJ DIAMOND\n"
                "10,000 PTS RHONDA RETURN\n"
                "10,000 PTS QUICKCLAW RETURN\n"
                " \n"  
                "LOSE PTS FOR FALLS/HAZARDS\n"
                " \n"  
                "PERFECT SCORE IS 199,000 POINTS.\n"
        },    
    
    {"BERZRK",  "BERZERK (C)1982 ATARI\n"
                " \n"  
                "GAME SELECT:\n"
                "GAME 1: EXTRA LIFE 1K. NO OTTO\n"
                "GAME 2: EXTRA LIFE 1K. NOR OTTO\n"
                "GAME 3: EXTRA LIFE 1K. INV OTTO\n"
                "GAME 4: EXTRA LIFE 2K. NO OTTO\n"
                "GAME 5: EXTRA LIFE 2K. NOR OTTO\n"
                "GAME 6: EXTRA LIFE 2K. INV OTTO\n"
                " \n"  
                "SCORING:\n"
                "EACH ROBOT      50 PTS EACH\n"
                "ALL ROBOT BONUS 10 PTS EACH\n"
        },
        
    {"CENTIP",  "CENTIPEDE (C)1982 ATARI\n"
                " \n"  
                "GAME SELECT:\n"
                "GAME 1: EASY PLAY\n"
                "GAME 2: STANDARD PLAY\n"
                " \n"  
                "SCORING:\n"
                "CENTIPEDE BODY    10 PTS\n"
                "CENTIPEDE HEAD   100 PTS\n"
                "SPIDER (DISTANT) 300 PTS\n"
                "SPIDER (MEDIUM)  600 PTS\n"
                "SPIDER (CLOSE!)  900 PTS\n"
                "FLEA             200 PTS\n"
                "SCORPION        1000 PTS\n"
                "MUSHROOM (DEST)    1 PTS\n"
                "MUSHROOM (WOUND)   5 PTS\n"
                "BONUS WAND EVERY 10,000 PTS\n"
        },
        

    {"COMMIE",  "COMMUNIST MUTANTS FROM SPACE\n"
                "(C)1982 STARPATH CORP \n"
                " \n"  
                "OPTIONS:\n"
                "PL  1   NUMBER OF PLAYERS\n"
                "DIF 1   DIFFICULTY LVL (9=HARD)\n"
                "SH NO   SHIELDS (PRESS DOWN)\n"
                "TW NO   TIME WARP (PRESS UP)\n"
                "PF NO   PENETRATING FIRE\n"
                "GF NO   GUIDED FIRE\n"
                " \n"  
                "SCORING:\n"
                "MOTHER CREATURE      500\n"
                "DIVING MUTANT ATTK    60\n"
                "MUTANT EGGS           10\n"
                "CLEARING THE SCREEN  100 \n"
                "BONUS LIFE AFTER ODD WAVES\n"
        },
    
    {"DEMONA",  "DEMON ATTACK (C)1981 IMAGIC\n"
                " \n"  
                "GAME SELECT:\n"
                "1  DEMON ATTACK\n"
                "3  TRACER SHOT DEMON ATTACK\n"
                "5  ADVANCED DEMON ATTACK\n"
                "7  ADVANCED TRACER DEMON ATTACK\n"
                "L-DIFF:  FASTER DEMON ATTACK\n"
                " \n"  
                "SCORING:\n"
                "WAVE  DEMONS  SPLIT  DIVE\n"
                "1-2    10     --     --\n"
                "3-4    15     --     --\n"
                "5-6    20     40     80\n"
                "7-8    25     50     100\n"
                "9-10   30     60     120\n"
                "11+    35     70     140\n"
        },


    {"COSARK",  "COSMIC ARK (C)1981 IMAGIC\n"
                " \n"  
                "SURVIVE THE METEOR SHOWER\n"
                "AND THEN RESCUE BOTH OF THE\n"  
                "BEASTIES ON THE PLANET!\n"  
                " \n"  
                "GAME SELECT:\n"
                "GAME 1: REGULAR MISSION\n"
                "GAME 2: METEOR SHOWER\n"
                "GAME 4: ADVANCED MISSION\n"
                "GAME 5: ADVANCED METEOR SHOWER\n"
                "L-DIFF: A=ARK SIZE WIDER\n"
                "SCORING:\n"
                "METEOR              10 PTS\n"
                "WAVE METEOR         30 PTS\n"
                "RESCUE BEASTIES:  1000 PTS\n"
        },

    {"CHOPER",  "CHOPPER COMMAND\n"
                "(C)1981 BY ACTIVISION\n"
                " \n"  
                "KNOCK OUT ENEMY AIRCRAFT\n"
                "WHILE PROTECTING TRUCKS.\n"
                " \n"  
                "GAME SELECT:\n"
                "GAME 1: CADET LEVEL\n"
                "GAME 3: COMMANDER LEVEL\n"
                "L-DIFF: A=SLOWER CHOPPER FIRE\n"
                " \n"  
                "SCORING:\n"
                "ENEMY COPTER       100 PTS\n"
                "ENEMY JET          200 PTS\n"
                "WAVE BONUS/TRUCK:  100 PTS\n"
                "BONUS SHIP EVERY 10000 PTS\n"
        },
    
    {"CROSSF",  "CROSS FORCE 1982 SPECTRAVISION\n"
                " \n"  
                "CATCH THE ENEMY IN A CROSSFIRE\n"
                "GAME 1: DIAGNONAL LASER\n"
                "GAME 2: PARALELL LASER\n"
                "L-DIFF: A=SLOW SPECTRON\n"
                " \n"  
                "WAVE NUMBER   SHIP   MORPUL\n"  
                "WAVE ONE       10     --   PTS\n"
                "WAVE TWO       20     20   PTS\n"
                "WAVE THREE     30     30   PTS\n"
                "WAVE FOUR+    +10    +10   PTS\n"
                " \n"
                "1K  - 10K     PURPLE HEART\n"
                "10K - 30K     CERT OF HONOR\n"
                "30K - 50K     MEDAL OF VALOR\n"
                "50K - 70K     SPECTRA MEDALLION\n"
                "70K - 100K    MEDAL OF KLIG\n"
        },
    
    
    {"ELAVAT",  "ELEVATORS AMISS\n"
                "(C)2007 BY BMONTGOMERY\n"
                " \n"  
                "GUIDE MAID MARIA TO THE TOP\n"
                "FLOOR WHILE AVOIDING ELEVATORS\n"  
                " \n"  
                "GAME     ELEV  BONUS\n"
                "NORMAL:   7     40 PTS\n"
                "EXPERT:   7     60 PTS\n"
                "CHILD:    2      0 PTS\n"
                "NOVICE:   4     20 PTS\n"
                " \n"  
                "SCORING:\n"
                "GET ACROSS FLOOR:  TIMER PTS\n"
                "GET TO TOP FLOOR:  BONUS PTS\n"
                " \n"  
                "PRESS JOY BUTTON FOR SPEED!\n"  
        },
    
    {"RABTRA",  "RABBIT TRANSIT (C)1983 ARCADIA\n"
                " \n"  
                "GUIDE YOUR BUNNY TO THE\n"
                "BUNNY BUSHES!\n"
                " \n"  
                "L-DIFF: A=TURTLE SUBMERGES\n"
                " \n"  
                "SCORING:\n"
                "EACH HOP SCORES POINTS\n"
                "BONUS POINTS FOR TIME REMAIN\n"
                " \n"  
                "EXTRA BUNNY AT 10,000 PTS\n"  
                " \n"        
        },
        
    {"SEAQST",  "SEA QUEST (C)1983 ACTIVISION\n"
                " \n"  
                "RESCUE DIVERS FROM SUBS AND\n"
                "SHARKS IN THE DEEP OCEAN.\n"
                "DON'T RUN OUT OF OXYGEN!\n"
                " \n"  
                "L-DIFF: A=SLOWER FIRE\n"
                " \n"  
                "SCORING:\n"
                "SUBS/SHARKS      10 PTS\n"
                "RESCUED DIVERS   50 PTS\n"
                "POINTS INCREASE WHEN YOU\n"  
                "BRING 6 DIVERS TO SURFACE\n"  
                "BONUS POINTS FOR OXYGEN REMAIN\n"  
        },
        
    {"RVRAID",  "RIVER RAID (C)1982 ACTIVISION\n"
                " \n"  
                "DESTROY ENEMIES AS YOU SEEK\n"  
                "BRIDGE AT END OF EVERY SECTION\n"
                "WATCH YOUR FUEL CONSUMPTION!\n"
                " \n"  
                "L-DIFF: A=UNGUIDED SHOTS\n"
                " \n"  
                "SCORING:\n"
                "TANKER       30 PTS\n"
                "HELICOPTER   60 PTS\n"
                "FUEL DEPOT   80 PTS\n"
                "JET         100 PTS\n"
                "BRIDGE      500 PTS\n"
                " \n"
                "BONUS JET EVERY 10,000 PTS\n"
    },
        
    {"CIRCUS",  "CIRCUS ATARI (C)1980 ATARI\n"
                " \n"  
                "POP  BALLOONS TO SCORE!\n"  
                " \n"  
                "L-DIFF: A=FASTER CLOWN BOUNCE\n"
                " \n"  
                "GAME 1: NORMAL BOUNCE\n"
                "GAME 2: EXTRA WALL\n"
                "GAME 3: BREAKTHRU (EASIER)\n"
                "GAME 4: BREAKTHRU + WALL\n"
                "GAME 5: MUST POP ALL BALOONS\n"
                "SCORING:\n"
                "TRAMPOLINE BOUNCE:   1 PTS\n"
                "RED BALOON POP:     10 PTS\n"
                "BLUE BALOON POP:     5 PTS\n"
                "WHITE BALOON POP:    2 PTS\n"
                "CLEAR ROW BONUS 100/50/20 PTS\n"
                " \n"
    },
    
    {"BRKOUT",  "BREAKOUT (C)1978 ATARI\n"
                " \n"  
                "L-DIFF: A=SMALLER PADDLE\n"
                " \n"  
                "GAME 1: NORMAL BREAKOUT\n"
                "GAME 2: STEERABLE BALL\n"
                "GAME 3: CATCHABLE BALL\n"
                "GAME 4: INSIVISBLE WALL\n"
                "GAME 5-8:  TIMED BREAKOUT\n"
                "GAME 9-12: BREAKTHRU\n"
                " \n"
                "SCORING:\n"
                "BLUE+AQUA BRICKS       1 PTS\n"
                "YELLOW+GREEN BRICKS    4 PTS\n"
                "RED+ORANGE BRICKS      7 PTS\n"
                " \n"
    },


    {"SUPBRK",  "SUPER BREAKOUT (C)1982 ATARI\n"
                " \n"  
                "L-DIFF: A=SMALLER PADDLE\n"
                " \n"  
                "GAME 1: NORMAL BREAKOUT\n"
                "GAME 3: DOUBLE BREAKOUT\n"
                "GAME 5: CAVITY BREAKOUT\n"
                "GAME 7: PROGRESSIVE BREAKOUT\n"
                "GAME 8: CHILDREN'S VERSION\n"
                " \n"
                "SCORING:\n"
                "BLUE+AQUA BRICKS       1 PTS\n"
                "YELLOW+GREEN BRICKS    4 PTS\n"
                "RED+ORANGE BRICKS      7 PTS\n"
                " \n"
    },
        
    {"BOWLNG",  "BOWLING (C)1980 ATARI\n"
                " \n"  
                "TEN FRAMES TO BOWL.\n"  
                "MAX SCORE IS 300 PTS!\n"  
                " \n"  
                "L-DIFF: A=HARDER TO STRIKE\n"
                " \n"  
                "SELECT:\n"
                "GAME 1: CURVE BALL\n"
                "GAME 3: STEER BALL\n"
                "GAME 5: STRAIGHT BALL\n"
                " \n"
    },
    
    {"MOONPA",  "MOON PATROL (C)1983 ATARI\n"
                " \n"  
                "L-DIFF: A=MUSIC OFF\n"
                "R-DIFF: A=TWO BUGGY SPEEDS\n"
                "CHOOSE EASY, MED, HARD GAME\n"
                " \n"
                " JUMPING   OBSTACLE    SHOOTING\n"
                " 100 PTS   SM CRATER   --- PTS\n"
                " 200 PTS   LG CRATER   --- PTS\n"
                "  50 PTS   LAND MINE   --- PTS\n"
                "  80 PTS   ROCK        100 PTS\n"
                " 100 PTS   TANK        200 PTS\n"
                " --- PTS   REGULAR UFO 100 PTS\n"
                " --- PTS   CRATER UFO  200 PTS\n"
                " --- PTS   ENEMY CAR 500/800/1K\n"
                " \n"
                "BONUS PTS FOR COMPLETE COURSE\n"
                "BONUS BUGGY AT 10K,30K,50K\n"
    },
    
    {"VANGRD",  "VANGUARD (C)1982 ATARI\n"
                " \n"  
                "REACH THE CITY OF MYSTERY AT\n"
                "TUNNEL END AND DESTROY GOND!\n"
                " \n"  
                "DIFF A,A: BUTTON+DIR = FIRE\n"
                "DIFF A,B: AUTO FORWARD FIRE\n"
                "DIFF B,A: BUTTON STOPS FIRE\n"
                "DIFF B,B: AUTO FORWARD FIRE\n"
                "          BUTTON STOPS FIRE\n"
                "HARLEY               50 PTS\n"
                "MIST                 70 PTS\n"
                "HELM,AMMO            80 PTS\n"
                "ROMEDA              100 PTS\n"
                "BARRIER             800 PTS\n"
                "GARIME,BASE     100-400 PTS\n"
                "DESTROY GOND  1000-8000 PTS\n"
                "BONUS LIFE 10K + 50K\n"
    },
        
    {"KABOOM",  "KABOOM! (C)1981 ACTIVISION\n"
                " \n"  
                "THE MAD BOMBER IS UP TO NO\n"
                "GOOD. STOP FALLING BOMGS IN\n"
                "WATER BUCKET USING PADDLES\n"
                " \n"  
                "L-DIFF A: SMALLER BUCKETS\n"
                "SCORING:\n"
                "GROUP  #BOMBS EACH TOTALPTS\n"
                "  1      10     1     10 PTS\n"
                "  2      20     2     40 PTS\n"
                "  3      30     3     90 PTS\n"
                "  4      40     4    160 PTS\n"
                "  5      50     5    250 PTS\n"
                "  6      75     6    450 PTS\n"
                "  7     100     7    700 PTS\n"
                "  8     150     8   1200 PTS\n"
                "EXTRA BUCKET EVERY 10K PTS\n"
    },

    {"SPIDFI",  "SPIDER FIGHTER\n"
                "(C)1981 ACTIVISION\n"
                "PROTECT YOUR FRUIT ORCHARD \n"
                "FROM INSECT FRUIT ATTACKERS!\n"
                " \n"  
                "L-DIFF A=EXPERT,   B=REGULAR\n"
                "R-DIFF A=STRAIGHT, B=GUIDED\n"
                "SCORING:\n"
                "MASTER NEST      100 PTS\n"
                "STINGER           50 PTS\n"
                "SPY POD           50 PTS\n"
                "GREEN WIDOW       30 PTS\n"
                "SAVE ALL 3 FRUIT AND GAIN\n"
                "EXTRA LIFE UP TO FOUR (ELSE\n"
                "YOU GAIN 500 BONUS PTS)\n"
                "EXPERT PTS X2 (GRAPE LV),\n"
                "X4 (STRAW LV),X8 (BANANAS)"
    },

    {"MEGAMA",  "MEGAMANIA (C)1981 ACTIVISION\n"
                "A SPACE NIGHTMARE - BLAST\n"
                "CRAZY OBJECTS FROM THE SKY!\n"  
                " \n"
                "GAME 1: GUIDED MISSILES\n"
                "GAME 3: STRAIGHT MISSILES\n"
                "L-DIFF A=SLOW MISSILES\n"
                "HAMBURGERS       20 PTS\n"
                "COOKIES          30 PTS\n"
                "BUGS             40 PTS\n"
                "RADIAL TIRES     50 PTS\n"
                "DIAMONDS         60 PTS\n"
                "STEAM IRONS      70 PTS\n"
                "BOW TIES         80 PTS\n"
                "SPACE DICE       90 PTS\n"
                "AFTER 1ST WAVE:  90 PTS\n"
                "EXTRA LIFE EVERY 10000 PTS\n"

    },
    
    {"MASH00",  "M.A.S.H. (C)1983 20TH CENTURY\n"
                " \n"
                "GUIDE YOUR CHOPPER TO RESCUE\n"  
                "WOUNDED ON THE BATTLEFIELD\n"
                "AND RETURN THEM TO MASH UNIT\n"
                " \n"
                "GAME 1: WELCOME TO KOREA\n"
                "GAME 3: COLONEL POTTER (HARD)\n"
                "GAME 5: CEASE FIRE\n"
                "GAME 7: OPERATING ROOM\n"
                "L-DIFF: START PTS (A=0,B=99)\n"
                "R-DIFF: START PTS (A=0,B=99)\n"
                " \n"
                "FIRST PLAYER TO 999 WINS!\n"
    },
    
    {"MOONSW",  "MOONSWEEPER (C)1983 IMAGIC\n"
                "RESCUE MINERS STRANDED ON \n"
                "MOONS IN STAR QUADRANT JUPITER\n"
                " \n"
                "GAME 1 BLUE, GREEN MOON (EASY)\n"
                "GAME 2 BLUE, GREEN AND YELLOW\n"
                "GAME 3 BLUE, GREEN AND YELLOW\n"
                "GAME 4 BLUE, GREEN, YEL, RED\n"
                " \n"
                "FORCE FIELD: BUTTON + JOY BACK\n"
                "PICKUP SIX MINERS TO END MOON\n"
                "PHASE AND ESCAPE GRAVITY VIA\n"
                "VIA THE ACCELERATION RINGS\n"
                " \n"
                "EXTRA MOONSWEEPER EVERY 10K PTS\n"
    },
    
    {"LASERG",  "LASER GATES (C)1983 IMAGIC\n"
                " \n"
                "DESTROY 4 FAILSAFE DETONATORS\n"
                "INSIDE THE COMPUTER BEFORE \n"
                "THEY SELF-DESTRUCT!\n"
                " \n"
                "SHIELDS PROTECT THE DANTE DART\n"
                "GAIN 6 SHIELD UNITS PER 10K PTS\n"
                " \n"
                "PASS FORCEFIELD         400 PTS\n"
                "DESTROY RADAR MORTAR    115 PTS\n"
                "DESTROY ROCK MUNCHER    325 PTS\n"
                "DESTROY BAT             330 PTS\n"
                "DESTROY HOMING MISSILE  525 PTS\n"
                "DESTROY DETONATOR      6507 PTS\n"
    },
    
    {"THUNGR",  "THUNDERGROUND (C)1983 SEGA\n"
                " \n"
                "DESTROY SIX ATOMIC REACTORS\n"
                "WHILE AVOIDING TANK FIRE!\n"
                " \n"
                "12 LEVELS OF DIFFICULTY WITH\n"
                "4 ROUNDS PER LEVEL\n"
                " \n"
                "ENEMY TANKS:     50  PTS\n"
                "SHOVEL TOKEN:   1000 PTS\n"
                "WALKIE TOKEN    2000 PTS\n"
                "KEY TOKEN       3000 PTS\n"
                "FLAG TOKEN      4000 PTS\n"
                "40 POINTS PER TIME TICK\n"
                "\n"
                "BASES DESTROYED ARE BETWEEN\n"
                "50 AND 7550 PTS DEPENDING ON\n"
                "LEVEL AND IF YOU HAVE TOKEN\n"
    },
    
    {"VENREL",  "VENTURE RELOADED (C)2020\n"
                " \n"
                "GUIDE WINKY THROUGH 9 LEVELS\n"
                "AND CAPTURE 36 TREASURES\n"
                " \n"
                "DIFF B,B: LEVEL 1\n"
                "DIFF B,A: LEVEL 2\n"
                "DIFF A,B: LEVEL 3\n"
                "DIFF A,A: LEVEL 4\n"
                " \n"
                "ENEMIES:        200 PTS\n"
                "TREASURES:      400 PTS\n"
                "LEVEL BONUS X LEVEL POINTS\n"
                " \n"
                "EXTRA LIFE EVERY 30K PTS\n"
                "ONLY IF LESS THAN 3 LIVES\n"
    },
    
    {"KAPERS",  "KEYSTONE KAPERS\n"
                "(C)1983 ACTIVISION\n"
                " \n"
                "HARRY HOOLIGAN IS AT IT\n"
                "APREHEND HIM, RECOVERY ITEMS\n"
                "AND AVOID ALL OBSTACLES.\n"
                " \n"
                "SCORING: KROOKS 1-8 ARE\n"
                "WORTH 100X AMOUNT LEFT ON \n"
                "BONUS TIMER. KROOKS 9-16 ARE\n"
                "WORTH 200X BONUS TIMER.\n"
                "KROOKS 16+ WORTH 300X BONUS.\n"
                "EACH RECOVERED ITEM IS 50 PTS\n"
                " \n"
                "BONUS KOP EVERY 10,000 PTS\n"
    },
    
    {"AARDVK",  "AARDVARK (C)2019\n"
                " \n"
                "GUIDE OSCAR'S TONGUE DOWN\n"
                "THE ANTHILL TO EAT EGGS.\n"
                " \n"
                "MODES: NOVICE, EASY, NORMAL,\n"
                "HARD, EXPERT, WILD1-2-3\n"
                " \n"
                "EGG           10 PTS\n"
                "ANT          100 PTS\n"
                "RED ANT      150 PTS\n"
                "CATERPILLAR  150 PTS\n"
                "WORM         200 PTS\n"
                "QUEEN       1000 PTS\n"
                "SPIDER       200 PTS\n"
                "BONUS = WORMS X ANTS\n"
                "EXTRA OSCAR BASED ON MODE\n"
    },
    
    {"TURMOI",  "TURMOIL (C)1982 20TH CENTURY\n"
                " \n"
                "ZIP UP AND DOWN TO WIPE OUT\n"
                "ALIENS AND COLLECT PRIZES.\n"
                " \n"
                "GAME SELECT IS USED TO \n"
                "CHOOSE STARTING LEVEL 1-9\n"
                " \n"
                "THE FASTER THE ALIENS MOVE,\n"
                "THE MORE POINTS THEY ARE WORTH\n"
                " \n"
                "EXTRA SHIP FOR LEVEL CLEAR\n"
    },
    
    {"CRAPOT",  "CRACKPOTS (C)1983 ACTIVISION\n"
                " \n"
                "HELP POTSY DROP POTTED PETUNIAS\n"
                "ON THE BUG INFESTATION!\n"
                " \n"
                "SCORING: BUG COLOR\n"
                "LV  BLACK  BLUE  RED  GREEN\n"
                " 1   10     20    30    40\n"
                " 2   20     40    60    80\n"
                " 3   30     60    90   120\n"
                " 4   40     80   120   160\n"
                " 5   50    100   150   200\n"
                " 6   60    120   180   240\n"
                " 7   70    140   210   280\n"
                " 8   80    160   240   320\n"
                " \n"
                "200 POINTS ARE AWARDED FOR EACH\n"
                "BUG REMAINING AT END OF WAVE\n"
    },

    {"ASTROB",  "ASTROBLAST (C)1982 MATEL\n"
                " \n"
                "DESTROY FALLING ROCKS\n"
                "L-DIFF:  A=AUTO FIRE\n"
                "R-DIFF:  A=FASTER PACE\n"
                "SCORE+     BG  SM  SP PUL UFO\n"
                "0  - 1K    10  20  40  80 ---\n"
                "1K - 5K    20  40  80 160 ---\n"
                "5K - 20K   30  60 120 240 ---\n"
                "20K- 50K   40  80 160 320 400\n"
                "50,000+    50 100 200 400 500\n"
                "SCORE-     BG  SM  SP  HIT\n"
                "0  - 1K     5  10 100  100\n"
                "1K - 5K    10  20 200  200\n"
                "5K - 20K   15  30 300  300\n"
                "20K- 50K   20  40 400  400\n"
                "50,000+    25  50 500  500\n"
                "EXTRA LIFE EVERY 1000 PTS\n"
    },

    {"BUCKRO",  "BUCK ROGERS (C)1983 SEGA\n"
                " \n"
                "ROUND 1: ELECTRON POSTS\n"
                "ROUND 2: POSTS + ALIEN SAUCERS\n"
                "ROUND 3: POSTS + SPACE HOPPERS\n"
                "ROUND 4: THE MOTHER SHIP!\n"
                "LEVEL ONE          20 POSTS\n"
                "LEVEL TWO          23 POSTS\n"
                "LEVEL THREE        28 POSTS\n"
                "LEVEL FOUR         33 POSTS\n"
                "LEVEL FIVE         28 POSTS\n"
                "LEVEL SIX+         31+3 POSTS\n"
                " \n"
                "SAUCER/HOPPER      300 PTS\n"
                "ELECTRON POST      500 PTS\n"
                "MOTHER SHIP        20K PTS\n"        
                "EXTRA SHIP EVERY   50K PTS\n"
    },
    
    {"CLIMB5",  "CLIMBER 5 (C)2004 D.DEBRO\n"
                " \n"
                "FETCH YOUR WAYWARD BASEBALL\n"
                "ON THE TOP LEFT GIRDER.\n"
                " \n"
                "GAME TYEPS: NOVICE, INTERMEDIATE\n"
                "AND ADVANCED\n"
                "L-DIFF:  A=GIRDERS WARNING OFF\n"
                " \n"
                "CATCH THESE IN ORDER:\n"
                "CUP                  100 PTS\n"
                "TEDDY BEAR           300 PTS\n"
                "BUTTERFLY            500 PTS\n"        
                "AA LOGO              700 PTS\n"        
                "HAMMER, BOX, BRICK     0 PTS\n"        
                "RETRIEVING BALL: BONUS VALUE\n"        
                "EXTRA LIVE AT 10,000 PTS\n"
    },
    
    {"COMRAI",  "COMMANDO RAID (C)1982 US GAMES\n"
                " \n"
                "THERE ARE EIGHT LEVELS OF PLAY\n"
                "EACH LEVEL HAS A DIFFERENT\n"
                "COLORED PARATROOPER SQUAD.\n"
                " \n"
                "B/W SWITCH FOR AUTO FIRE\n"
                "L-DIFF:  A=STRAIGHT BULLETS\n"
                "R-DIFF:  A=NO BOMBER\n"
                " \n"
                "HELICOPTER/BOMBER      200 PTS\n"        
                "COMMANDO PARATROOPER   115 PTS\n"        
                "EXTRA BUILDING EVERY   10K PTS\n"
    },
   
    {"CONMAR",  "CONQUEST OF MARS (C)2006 CHAMP\n"
                " \n"
                "THERE ARE SIX DEEP CAVERNS TO\n"
                "NAVIGATE AND ACTIVATE THE BOMB!\n"
                " \n"
                "UP/DN SELECT DIFFICULTY LEVEL\n"
                "B/W SWITCH TO PAUSE GAME\n"
                "L-DIFF:  A=CANNONS WILL FIRE!\n"
                "TRAVEL ONE PARSEC       10 PTS\n"        
                "FUEL BUNKER            150 PTS\n"        
                "GENERATOR              200 PTS\n"
                "CANNON / ROCKET        250 PTS\n"
                "SPACE MINE             300 PTS\n"
                "2 STAGES CLEAR        2000 PTS\n"
                "3 STAGES CLEAR        4000 PTS\n"
                "4 STAGES CLEAR        8000 PTS\n"
                "5 STAGES CLEAR       15000 PTS\n"
                "ESCAPE TIME BONUS 500/SEC\n"
    },

    {"CONDOR",  "CONDOR ATTACK (C)1982 CHAMP\n"
                " \n"
                "A RIFT IN TIME HAS CAUSED\n"
                "PREHISTORIC CONDOR ATTACK!\n"
                " \n"
                "DIFF SWITCHES:  A,A=FATTER BASE\n"
                " \n"
                "SMALL UPPER ATTACKER   3 PTS\n"
                "LV 1 LARGE ATTACKER   10 PTS\n"
                "LV 2 LARGE ATTACKER   20 PTS\n"
                "LV 3 LARGE ATTACKER   40 PTS\n"
                "LV 4 LARGE ATTACKER   50 PTS\n"
                "LV 5 LARGE ATTACKER   60 PTS\n"
                "LV 6 LARGE ATTACKER   70 PTS\n"
                "LV 7 LARGE ATTACKER   80 PTS\n"
                "LV 8 LARGE ATTACKER   90 PTS\n"
                "LV 9 LARGE ATTACKER   99 PTS\n"
                "EXTRA FIREBASES EVERY 1000 PTS\n"   
    },
    
    {"DSTOMP",  "DRAGONSTOMPER (C)1982 ARCADIA\n"
                 " \n"
                 "PART ONE: ENCHANTED COUNTRYSIDE\n"
                 "PART TWO: THE OPPRESSED VILLAGE\n"
                 "PART THREE: THE DRAGON'S CAVE\n"
                 " \n"
                 "JOYSTICK TO MOVE, FIGHT OR USE\n"
                 "AN ITEM OR MAGIC SPELL. CHECK\n"
                 "STATUS OFTEN - IF STR DROPS TO\n"
                 "BELOW 0 YOU DIE. TO RESSURECT\n"
                 "IN FIRST PART, PRESS RESET BUT\n"
                 "YOU LOSE ALL MAGIC OBJECTS.\n"
    },
    
    {"FANVOY",  "FANTASTIC VOYAGE (C)1982 20TH\n"
                "INJECTED INTO THE BLOODSTREAM\n"
                "YOU RACE TO SAVE THE PATIENT!\n"
                " \n"
                "GAME 1 = NORMAL GAME\n"
                "GAME 2 = EXTENDED GAME\n"
                "GAME 3 = DIFFICULT VERSION \n"
                "GAME 4 = EXTENDED DIFFICULT\n"
                "SIX PHASES:\n"
                "PH1: DEFENSE CELLS :    SHOOT\n"
                "PH2: BLOOD CELLS   : NO SHOOT\n"
                "PH3: BACTERIA      :    SHOOT\n"
                "PH4: MIX OF CELLS  : NO/SHOOT\n"
                "PH5: NARROW ARTERY : NO/SHOOT\n"
                "PH6: BLOOD CLOT    :    SHOOT\n"
                "FIRST PATIENT:  PH1,2,5,6\n"
                "SECOND PATIENT: PH1,2,3,5,6\n"
                "THIRD+ PATIENT: PH1,2,3,4,5,6\n"
    },
    
    {"FATHOM",  "FATHOM (C)1983 IMAGIC\n"
                " \n"
                "LOCATE THE 3 MISSING PIECES\n"
                "NEPTUNE'S TRIDENT AND FREE\n"
                "HIS DAUGHTER 7 TIMES.\n"
                "SWITCH FROM DOLPHIN TO GULL\n"
                "PRESSING BUTTON AT SURFACE\n"
                " \n"
                "SCORING:\n"
                "EACH TIME YOU FREE NEPTINA\n"
                "YOUR LEVEL POINTS ARE ADDED\n"
                "TO ALL PREVIOUS POINTS. HIGHER\n"
                "LEVELS MULTIPLY TO MORE POINTS\n"
    },   
    
    {"FREWAY",  "FREEWAY (C)1981 ACTIVISION\n"
                " \n"
                "WHY DID THE CHICKEN CROSS\n"
                "THE ROAD?!\n"
                " \n"
                "L-DIFF: A=FULL CURB KNOCK BACK\n"
                "GM1: LAKE SHORE DRIVE, CHICAGO\n"
                "GM2: INTERSTATE 5, SEATTLE\n"
                "GM3: SANTA MONICA FREEWAY, LA\n"
                "GM4: BAYSHORE FREEWAY, SANFRAN\n"
                "GM5: JOHN LODGE EXWAY, DETROIT\n"
                "GM6: THE BELTWAY, WASHINGTON\n"
                "GM7: LBJ FREEWAY, DALLAS\n"
                "GM8: LONG ISLAND EXWAY, NYC\n"
    },  
    
    {"KILLER",  "KILLER SATELLITES (C)1983 AR\n"
                " \n"
                "DESTROY ALL SKY OBJECTS TO\n"
                "SAVE GROUND OBJECTS.\n"
                " \n"
                "USE GAME SELECT TO PICK\n"
                "THE STARTING WAVE.\n"
                "L-DIFF: A=FASTER SHIP\n"
                "R-DIFF: A=SLOWER FIRE\n"
                " \n"
                "SKY OBJECTS WORTH 10-90PTS\n"
                "EACH GROUND OBJECT SAVED 50PTS\n"
                "EACH WAVE IS 100 PTS X WAVE\n"
                "BONUS FOR UNUSED FUEL.\n"
                "EXTRA LIFE EVERY 10,000 PTS\n"
    },
    
    {"HAUNTH",  "HAUNTED HOUSE (C)1982 ATARI\n"
                " \n"
                "FIND THE THREE PIECES OF THE\n"
                "MAGIC URN AND BRING BACK TO THE\n"
                "MAIN ENTRANCE OF THE MANSION.\n"      
                "USE SCEPTER FOR PROTECTION.\n"      
                "USE KEY TO OPEN LOCKED DOORS.\n"
                " \n"
                "L-DIFF: A=NO LIGHT FLASH\n"
                "GM1 - LIGHTED WALLS, NO DOORS\n"
                "GM2 - ALL DARK, UNLK DOORS\n"
                "GM3 - ALL DARK, LOCK DOORS\n"
                "GM4 - RANDOM MASTER KEY\n"
                "GM5 - EXTRA SPIDERS\n"
                "GM6 - CREATURS CROSS ROOMS\n"
                "GM7 - BAT CAUSES OBJ DROP\n"
                "GM8 - FASTER CREATURES\n"
                "GM9 - ULTIMATE CHALLENGE!\n"
    },
    
    {"GALAXY",  "GALAXIAN (C)1983 ATARI\n"
                " \n"
                "GAME SELECT = WAVE NUMBER\n"
                "L-DIFF: A=NO AUTO FIRE\n"
                " \n"
                "SCORE     FORMATION  IN-FLIGHT\n"
                "GREEN ROWS   30 PTS    60  PTS\n"
                "PURPLE ROWS  40 PTS    80  PTS\n"
                "RED ROW      50 PTS    100 PTS\n"
                "WHITE ROW    60 PTS    120 PTS\n"
                "FLAGSHIP     200/300/800 PTS\n"
                " \n"
                "EXTRA LIFE AT 7000 PTS\n"
    },

    {"PACMAN",  "PAC-MAN (C)1982 ATARI\n"
                " \n"
                "L-DIFF: A=ADVANCED GAME\n"
                "GM1: SLOW PAC, SLOW GHOSTS\n"
                "GM2: SLOW PAC, FAST GHOSTS\n"
                "GM3: FAST PAC, SLOW GHOSTS\n"
                "GM4: FAST PAC, FAST GHOSTS\n"
                "GM5: FAST PAC, FASTER GHOSTS\n"
                "GM6: FAST PAC, FASTEST GHOSTS\n"
                " \n"
                "VIDEO WAFER        1 PT\n"
                "POWER PILL         5 PTS\n"
                "VITAMINS         100 PTS\n"
                "FIRST GHOST       20 PTS\n"
                "SECOND GHOST      40 PTS\n"
                "THIRD GHOST       80 PTS\n"
                "FOURTH GHOST     160 PTS\n"
                "EXTRA LIFE EVERY BOARD CLEAR\n"
    },
    
    {"PHOENX",  "PHOENIX (C)1982 ATARI\n"
                " \n"
                "L-DIFF: A=BIRD SOUND OFF\n"
                "PRESS DOWN FOR SHIELD\n"
                " \n"
                "SCORING VARIES DEPENDING\n"
                "ON WAVE, SWOOPING BIRDS,\n"
                "PROXIMITY TO SHIP, ETC.\n"
    },
    
    {"QUICKS",  "QUICK STEP! (C)1983 IMAGIC\n"
                " \n"
                "CHANGE TRAMPOLINES COLOR AS\n"
                "YOU JUMP ON THEM. LAND ON THE\n"
                "PINK TRAMPOLINES TO SCORE."
                " \n"
                "BONUS OF 200 PTS FOR EACH\n"
                "LIFE LEFT WHEN OPP DIES.\n"
                "BONUS LIFE AT 2000 PTS\n"
    },
    
    {"STAVOY",  "STAR VOYAGER (C)1982 IMAGIC\n"
                " \n"
                "PENETRATE THE 7 STAR PORTALS\n"
                "AND SAVE CAPITAL STARPORT!\n"
                " \n"
                "L-DIFF: A=ACCELERATED ACTION\n"
                "R-DIFF: A=LASERS, B=PHOTONS\n"
                "SCORE: NUMBER OF ENEMIES * 5\n"
                "       +10 PER STAR PORTAL\n"
                "  0-15     AWOL\n"
                " 16-47     (ONE CHEVRON)\n"
                " 48-79     (TWO CHEVRONS)\n"
                " 80-111    (THREE CHEVRONS)\n"
                "112-143    (FOUR CHEVRONS)\n"
                "144-175    LIEUTENANT\n"
                "176-207    CAPTAIN\n"
                "208-       ADMIRAL\n"
    },
    
    {"MSPACM",  "MS PAC MAN (C)1982 ATARI\n"
                "GM CHERRIES - NORMAL GAME \n"
                "GM 1 BEAR   - BEGINNER \n"
                "GM 2 BEARS  - NOVICE \n"
                "GM 3 BEARS  - INTERMEDIATE \n"
                " \n"
                "DOT                   10 PTS\n"
                "ENERGY PILL           50 PTS\n"
                "CHERRY               100 PTS\n"
                "STRAWBERRY           200 PTS\n"
                "ORANGE               500 PTS\n"
                "PRETZEL              700 PTS\n"
                "APPLE               1000 PTS\n"
                "PEAR                2000 PTS\n"
                "BANANA              5000 PTS\n"
                "GHOSTS  200/400/800/1600 PTS\n"
                "EXTRA LIFE AT 10,000 PTS\n"
    },
    
    {"SOLARI",  "SOLARIS (C)1986 ATARI\n"
                " \n"
                "HYPERWARP ACROSS SECTORS OF\n"
                "THE GALAXY TO REACH SOLARIS!\n"
                " \n"
                "CORRIDOR NAVIGATE     8,000 PTS\n"
                "RESCUING ALL CADETS   8,000 PTS\n"
                "FLAGSHIP                500 PTS\n"
                "RAIDER                  400 PTS\n"
                "KOGALON STAR PIRATE     320 PTS\n"
                "TARGETER                320 PTS\n"
                "GLIDER                  320 PTS\n"
                "MECHNOID                300 PTS\n"
                "BLOCKADER               260 PTS\n"
                "COBRA SHIP               80 PTS\n"
                "GUARDIAN                 60 PTS\n"
                "DISTRACTOR               20 PTS\n"
                "PRESS Y BUTTON FOR GALACTIC MAP\n"
    },
    
    {"RAIDER",  "RAIDERS OF THE LOST ARK (C)1986\n"
                " \n"
                "HELP INDY FIND THE LOST ARK!\n"
                "USE X,Y,A,B TO MANAGE INVENTORY\n"
                " \n"
                "FLUTE PROTECTS FROM SNAKES\n"
                "COINS ARE USED TO BUY ITEMS\n"
                "GRENADE TO BLAST BARRIERS\n"
                "KEY USED TO OPEN DOORS\n"
                "WHIP CLOSE COMBAT ATTACK\n"
                "PARACHUTE TO LAND SAFELY\n"
                "TIMEPIECE TELLS IN-GAME TIME\n"
                "REVOLVER LONG RANGE ATTACK\n"
                "BULLETS FOR THE REVOLVER\n"
                "ANKH TRANSPORT TO MESA FIELD\n"
                "CHAI TRANSPORT TO BLACK MARKET\n"
                "HOURGLASS OBTAIN GRAPLING HOOK\n"
                                          "SHOVEL IS USED FOR DIGGING\n"
    },
    
    {"WIZWOR",  "WIZARD OF WOR (C)1982\n"
                " \n"
                "OUTWITTING AND OUTBLAST THE\n"
                "SINISTER WIZARD OF WOR!\n"
                " \n"
                "L-DIFF:  A=HARDER ENEMIES\n"
                " \n"
                "SCORING:\n"
                "BLUE BURWORS        100 PTS\n"
                "YELLOW GARWORS      200 PTS\n"
                "RED THORWORS        500 PTS\n"
                "WORLUK             1000 PTS\n"
                "WIZARD OF WOR      2500 PTS\n"
                "EXTRA LIFE AT 10,000 PTS\n"
    },

    {"CARNIV",  "CARNIVAL (C)1982 COLECO\n"
                " \n"
                "CLEAR THE RACK OF ALL TARGETS\n"
                "AND PIPES TO ADVANCE LEVEL.\n"
                " \n"
                "SCORING:\n"
                "TARGET       LV1  LV2  LV3  LV4\n"
                "PIPE         200  200  200  200\n"
                "BOTTOM ROW    20   30   40   50\n"
                "MIDDLE ROW    40   50   60   70\n"
                "TOP ROW       60   70   80   90\n"
                "EXTRA BULLET   8    8    8    8\n"
                " \n"
                "TWO CONSECUTIVE PIPES OF SAME\n"
                "COLOR EARN BONUS OF 200/800 PTS\n"
                "GALLERY CLEAR BONUS 50 PTS/SHOT\n"
    },
    
    {"Z-TACK",  "Z-TACK (C)1983 BOMB\n"
                " \n"
                "GAME 1:  BEGINNER\n"
                "GAME 3:  ADVANCED\n"
                " \n"
                "THERE ARE 6 DISTINCT LEVELS\n"
                "IN ONE COMPLETE CYCLE AND THE\n"
                "GAME PATTERN WILL RECYCLE.\n"
                " \n"
                "MAXIMUM SCORE IS 999,999\n"
    },
    
    {"WALDEF",  "WALL DEFENDER (C)1983 BOMB\n"
                " \n"
                "THE OUTER WALL TAKE 10 HITS\n"
                "SUPER ALIEN TAKES OUT WALL\n"
                "WALL COLOR DEEPS WITH DAMAGE\n"
                "MOVE TO INNER WALL WHEN THE\n"
                "OUTER WALL IS ALMOST GONE.\n"
                " \n"
                "MAXIMUM SCORE IS 999,999\n"
    },
    
    {"EARTHW",  "EARTH WORLD (C)1982 ATARI\n"
                "TRAVERSE THE 12 ROOMS OF THE\n"
                "ZODIAC. A VARIETY OF MAGICAL\n"
                "OBJECTS ASSIST YOUR QUEST.\n"
                "BY LEAVING THE RIGHT OBJECTS\n"
                "IN THE RIGHT ROOMS, YOU GET\n"
                "CLUES TO PUZZLES. THIS GAME\n"
                "REQUIRES USE OF THE COMIC\n"
                "THAT CAME WITH IT.\n"
                " \n"
                "FINAL SEQUENCE TRIGGERS WHEN\n"
                "YOU HAVE PERFORMED 15 TRIALS\n"
    },

    {"FIREWO",  "FIRE WORLD (C)1982 ATARI\n"
                " \n"
    },

    {"WATERW",  "WATER WORLD (C)1983 ATARI\n"
                " \n"
    },

    {"STARTR",  "STAR TREK (C)1983 SEGA\n"
                " \n"
                "DESTROY NOMAD! SIX ROUNDS\n"
                "OF ADVENTURE AS FOLLOWS:\n"
                "1-2 : KLINGON ENCOUNTER\n"
                "3   : ASTEROIDS/METEORS\n"
                "4-5 : KLINGON ENCOUNTER\n"
                "6   : NOMAD!\n"
                " \n"
                "SHIELD CONDITIONS:\n"
                "YELLOW     : 3+ STRENGTH\n"
                "ORANGE     : 2  STRENGTH\n"
                "LIGHT RED  : 1  STRENGTH\n"
                "DARK RED   : DEFENSES DOWN!\n"
                "DOCK W STARBASE TO REFUEL\n"
    },
    
    {"SPJOCK",  "SPACE JOCKEY (C)1982 USGAMES\n"
                " \n"
                "L-DIFF:  A=FASTER ENEMY SHOT\n"
                "R-DIFF:  A=FREQUENT ENEMY SHOT\n"
                " \n"
                "GAME 1:  NORMAL\n"
                "GAME 2:  GUIDED SHOT\n"
                "GAME 3:  RANDOM ENEMIES\n"
                "GAME 5:  HORIZONTAL MOVE\n"
                "GAME 9:  COLLISIONS ON\n"
                "GAME 16: THE KITCHEN SINK!\n"
                "SCORING:\n"
                "JET PLANE       100 PTS\n"              
                "HELICOPTER       50 PTS\n"
                "PROP PLANE      100 PTS\n"              
                "BALLOON          25 PTS\n"
                "TANK            100 PTS\n"              
                "HOUSE/TREE       20 PTS\n"
    },
    
    {"PLAQUE",  "PLAQUE ATTACK (C)1983 ACTIVSN\n"
                " \n"
                "YOU HAVE 35 SECONDS TO WIPE\n"
                "OUT EACH WAVE OF FOOD!\n"
                "L-DIFF:  A=SLOWER FIRE\n"
                "GAME 1:  NORMAL\n"
                "GAME 3:  BEGINNER GAME\n"
                "SCORING:\n"
                "WV FOOD        HIT  SECS TEETH\n"
                "1  HAMBURGERS    5     5    5\n"
                "2  HOT DOGS     10    10   20\n"
                "3  FRIES        15    15   45\n"
                "4  STRAWBERRIES 20    20   80\n"
                "5  GUM DROPS    25    25  125\n"
                "6  DONUTS       30    30  150\n"
                "7  CANDY CANES  35    35  175\n"
                "8  ICE CREAM    40    40  200\n"
                "BONUS TOOTH EVERY 2000 POINTS\n"
    },
    
    
    {"BERMUD",  "BERMUDA TRIANGLE (C)1982 DATA\n"
                " \n"
                "COLLECT SUNKEN TREASURES FROM\n"
                "THE OCEAN FLOOR AND DELIVER\n"
                "TO A RESEARCH SHIP ON SURFACE\n"
                "WATCH OUT FOR MINES AND ENEMY\n"
                "SHIPS THAT STEAL YOUR CARGO.\n"
                "L-DIFF:  A=ADVANCED GAME\n"
                "GAME 1:  LASERS AFTER 10,000\n"
                "GAME 3:  LASERS AT START\n"
                " \n"
                "SCORING:\n"
                "KILLER SHARK         200 PTS\n"
                "GIANT SQUID          200 PTS\n"
                "AQUATIC DRONE        200 PTS\n"
                "ARTIFACT TO SURFACE  600 PTS\n"
                " \n"        
                "EXTRA LIFE EVERY 10000 PTS\n"
    },
    
    {"TACSCN",  "TAC-SCAN (C)1982 BY SEGA\n"
                " \n"
                "WIPE OUT 10 ENEMY SHIPS ANDN"
                "BRING IN REINFORCEMENTS ON\n"
                "EACH OF 15 POSSIBLE LEVELS.\n"
                "\n"
                "SCORING:\n"
                "LEVEL  1HIT ROUND 3HIT 4HIT\n"
                "LV1    100  1000  10K  20K PTS\n"
                "LV2    200  2000  10K  20K PTS\n"
                "LV3    300  5000  10K  20K PTS\n"
                "LV4    400 20000  10K  20K PTS\n"
                "LV5+   ETC 20000  10K  20K PTS\n"
                " \n"        
                "COLORED SHIP BONUS IS 500 PTS\n"
                "HIGHER SCORES FOR HITTING 3 OR\n"
                "4 ENEMIES WITH ONE SALVO.\n"
    },

    {"SEAHWK",  "SEA HAWK (C)1983 BY FROGGO\n"
                " \n"
                "DODGE ENEMY FIRE AND USE YOUR\n"
                "GUNS AND TORPEDOS TO SURVIVE.\n"
                " \n"
                "INTENSITY INCREASES AT 10K\n"
                "AND AGAIN AT 30K. PRESS BUTTON\n"
                "ALONG WITH LEFT/RIGHT TO FIRE.\n"
                " \n"
                "L-DIFF:  A=FASTER GAME\n"
                "USE SELECT FOR TORPEDO SIZE\n"
                " \n"
                "POINTS SCALE UP AS YOU GO FROM\n"
                "LEVEL 1,2,3 - BE CAREFUL NOT TO\n"
                "SHOOT DOWN YOUR OWN SHIPS!\n"
                " \n"
                "BONUS LIFE EVERY 20 HELICOPTERS\n"
    },
    
    
    {"SABOTR",  "SABOTEUR (C)1983 BY ATARI\n"
                "COMPLETED PROTOTYPE GAME.\n"
                "RACE AGAINST TIME TO DISARM\n" 
                "WARHEADS ACROSS THREE SCREENS.\n"
                "L-DIFF: A=29 SECS  B=38 SECS\n"
                "GAME 1:  NORMAL\n"
                "GAME 2:  SHOTS REFLECT\n"
                "GAME 3:  SIDE BULLETS APPEAR\n"
                "GAME 4:  INSANE SPEED!\n"
                "QOTILE ROBOT:       23 PTS\n"
                "YAR FLY:           198 PTS\n"
                "MASTER ROBOT:       57 PTS\n"
                "SIDE BULLET:        33 PTS\n"
                "GORFON SAFE TRIP:   71 PTS\n"
                "ROCKET DISTANCE:    22 PTS\n"
                "WARHEAD PIECES: 33/495 PTS\n"
                "TIME LEFT:          99 PTS\n"
                "DESTROY WARHEAD:   600 PTS\n"
    },
    
    
    {"POLEPO",  "POLE POSITION (C)1983 ATARI\n"
                " \n"
                "QUALIFYING LAP AND GRAND PRIX\n"
                "YOU EARN 10,000 PTS FOR LAP\n"
                "AND 50 PTS FOR EACH CAR PASSED.\n"
                "QUALIFYING LAP IS 90 SECS BUT\n"
                "YOU MUST COMPLETE IN 73 SECS TO\n"
                "QUALIFY FOR A POLE POSITION!\n"
                " \n"
                "JOYSTICK UP FOR LOW GEAR\n"
                "JOYSTICK DN FOR HIGH GEAR\n"
                "USE BUTTON TO BRAKE CAR\n"
                " \n"
    },
    
    {"MINDMA",  "ESCAPE FROM THE MIND MASTER\n"
                "(C)1983 BY STARPATH \n"
                " \n"
                "CARRY AND FIT GEOMETRIC KEYS\n"
                "INTO MATCHING SLOTS ON WALLS\n"
                "TO UNLOCK DOOR TO NEXT LEVEL.\n"
                "WATCH OUT FOR THE MINDMASTERS\n"
                "TRICKY MINI-GAMES AND BEWARE\n"
                "THE LOST ALIEN ALSO TRAPPED\n"
                "IN THE MAZE. WHEN YOU FINALLY\n"
                "ARE DONE, THE MINDMASTER WILL\n"
                "EVALUATE YOUR ATTEMPT!\n"
    },
    

    {"POLARI",  "POLARIS (C)1982 TIGERVISION\n"
                " \n"
                "WATCH OUT FOR DANGER FROM\n"
                "ABOVE AND BELOW!\n"
                "BOMBER SQUADRON:   300/200/100\n"
                "ENEMY SUBMARINES:  100/200/300\n"
                "ENEMY DESTROYER:       800 PTS\n"
                "CHANNEL MINES:         300 PTS\n"
                "DIVE BOMBER:          1000 PTS\n"
                " \n"
                "LV  PLANES  BOMBS  SUBS  SPEED\n"
                " 1    2      1     1     SLOW\n"
                " 2    3      1     1     SLOW\n"
                " 3    4      1     2     SLOW\n"
                " 4    5      1     3     SLOW\n"
                "5-8   ETC    ETC   ETC   MED \n"
                "9-12  ETC    ETC   ETC   FAST\n"
                "13-16 ETC    ETC   ETC   VFAST\n"
    },

    {"LEAD01",  "LEAD (C)2008 S. SERRA\n"
                " \n"
                "SURVIVE WAVE AFTER WAVE OF\n"
                "ONCOMING ENENIES!\n"
                " \n"
                "1ST STAGE:  FIRE STAGE\n"
                "2ND STAGE:  DODGE STAGE\n"
                "3RD STAGE:  SCRAMBLE STAGE\n"
                "4TH STAGE:  CATCH STAGE\n"
                " \n"
                "L-DIFF:  A=EXPERT GAME\n"
                "R-DIFF:  A=SAFE SMART BOMB\n"
                " \n"
                "YOU GET 3 PTS FOR ENEMIES ON\n"
                "STAGES 1-3 AND 5 PTS ON STAGE\n"
                "4 PLUS A STAGE CLEAR BONUS.\n"
                "DOWN ACTIVATES SMART BOMB BUT\n"
                "CAUSES SCORE TO ROUND DOWN.\n"
    },
    
    {"GOFISH",  "GO FISH (C)2007 B.MONTGOMERY\n"
                "EAT OR BE EATEN!\n"
                "L-DIFF:  A=START AS BIG FISH\n"
                " \n"
                "FISH POINTS AND ADVANCE SCORE:\n"
                "LV1:  1 PTS    5 PTS TINY WHITE\n"
                "LV2:  2 PTS   19 PTS TINY GREEN\n"
                "LV3:  4 PTS   55 PTS TINY YELLW\n"
                "LV4:  7 PTS  132 PTS TINY RED\n"
                "LV5: 10 PTS  262 PTS MED  GREEN\n"
                "LV6: 15 PTS  487 PTS MED BLACK\n"
                "LV7: 20 PTS  827 PTS MED WHITE\n"
                "LV8: 25 PTS 1302 PTS MED BROWN\n"
                "LV9: 35 PTS 2037 PTS BIG PINK\n"
                "L10: 45 PTS 3071 PTS BIG GREEN\n"
                "L11: 55 PTS 4446 PTS BIG GREY\n"
                "L12: 65 PTS 6203 PTS BIG RED\n"
                "L13: 80 PTS ---- PTS HUGE RED\n"
    },

    {"HELWAY",  "HELLWAY (C)2021\n"
                "M0:  CYCLE TRAFFIC\n"
                "M1:  CONSTANT TRAFFIC\n"
                "M2:  M0 + RANDOM TRAFFIC\n"
                "M3:  M1 + RANDOM TRAFFIC\n"
                "M4:  M0+BIGGER SPEED DIFFS\n"
                "M5:  M1+BIGGER SPEED DIFFS\n"
                "M6:  M2+BIGGER SPEED DIFFS\n"
                "M7:  M3+BIGGER SPEED DIFFS\n"
                "M8:  M0+RANDOM CHKPT INTENSITY\n"
                "M9:  M1+RANDOM CHKPT INTENSITY\n"
                "MA:  M2+RANDOM CHKPT INTENSITY\n"
                "MB:  M3+RANDOM CHKPT INTENSITY\n"
                "MC:  M4+RANDOM CHKPT INTENSITY\n"
                "MD:  M5+RANDOM CHKPT INTENSITY\n"
                "ME:  M6+RANDOM CHKPT INTENSITY\n"
                "MF:  M7+RANDOM CHKPT INTENSITY\n"
                "DIF: BB 29S       DIF BA 34S\n"
                "DIF: AB 39S       DIF AA 44S\n"
    },

    {"SPGAME",  "SPACEGAME (C)2020 KARL G\n"
                "DESTROY INVADING ENEMIES AND\n"
                "DONT LET SMART BOMB HIT GROUND\n"
                "L-DIFF:  A=DOUBLE WIDE SHIP\n"
                "R-DIFF:  A=ENEMIES SHOOT FAST\n"
                " \n"
                "POWER UPS: DOUBLE SHIP, WIDE\n"
                "SHIP, FAST SHIP, SLOW SHIP,\n"
                "BAD NAV, BLAST SHIELD, BAD\n"
                "GUNS, POWER DOWN, RANDOM ???\n"
                " \n"
                "SCORING:\n"
                "EACH ALIEN:        75 PTS\n"
                "GROUP ALIENS:      50 PTS\n"
                "BOSS KILL:        500 PTS\n"
                "NO COLLISIONS:    300 PTS\n"
                "EACH COLLISION:   -50 PTS\n"
                "EXTRA LIFE AT 20K AND 100K\n"
    },

    {"ALIEN0",  "ALIEN (C)1982 20TH CENT FOX\n"
                "IN SPACE... NO ONE CAN HEAR\n"
                "YOU SCREAM!  CLEAR EGGS.\n"
                "L-DIFF: A=RANDOM ALIEN MOVE\n"
                "R-DIFF: A=PULSAR HAS NO EFFECT\n"
                "GAME 1: NORMAL GAME\n"
                "GAME 2: ADVANCED GAME\n"
                "GAME 3: EXPERT GAME\n"
                "EGGS:               10 PTS\n"
                "PULSAR:            100 PTS\n"
                "1ST ALIEN:         500 PTS\n"
                "2ND ALIEN:        1000 PTS\n"
                "3RD ALIEN:        2000 PTS\n"
                "COMPLETE SCREEN:     1 PTS\n"
                "ROCKET:            500 PTS\n"
                "SATURN:           1000 PTS\n"
                "STARSHIP:         2000 PTS\n"
                "EXTRA LIFE AFTER 2ND SCREEN\n"
    },

    {"BEANYB",  "BEANY BOPPER (C)1982 20TH CENT\n"
                "CAPTURE BEANIES+FALLING OBJS\n"
                "OPTION 1: BEANIES BOUNCE\n"
                "OPTION 2: BEANIES DON'T BOUNCE\n"
                "ADVANCEMENT:\n"
                "LEVEL 0 =  0-999          PTS\n"
                "LEVEL 1 =  1,000 - 2,999  PTS\n"
                "LEVEL 2 =  3,000 - 4,999  PTS\n"
                "LEVEL 3 =  5,000 - 9,999  PTS\n"
                "LEVEL 4 = 10,000 - 19,999 PTS\n"
                "LEVEL 5 = 20,000 - 29,999 PTS\n"
                "LEVEL 6 = 30,000 - 49,999 PTS\n"
                "LEVEL 7 = 50,000+         PTS\n"
                "BEANY STUNNED/CAPTURED: 20/100+\n"
                "FALLING OBJ STUN/CAPT:  20/100+\n"
                "ORANGE EYE STUN/CAPT:  100/100+\n"
                "SURPRISE AT 100,000 POINTS!\n"
                "EXTRA BOPPER EVERY 4 BEANIES\n"
    },

    {"DEMDIA",  "DEMONS 2 DIAMONDS (C)1982 ATARI\n"
                " \n"
                "HIT DEMONS OF YOUR COLOR AND\n"
                "THEN HIT DIAMOND FOR BONUS PTS\n"
                " \n"
                "L-DIFF: A=FASTER DEMON FIRE\n"
                "GAME 1: NORMAL GAME\n"
                "GAME 4: EASY GAME\n"
                "DEMON OF YOUR COLOR:  1-8  PTS\n"
                "PULSATING DIAMONDS:  10-80 PTS\n"
                "HIGHER POINT VALUES FOR\n"
                "WHAT LEVEL THE OBJECT IS ON\n"
    },

    {"FROSTB",  "FROSTBITE (C)1982 ACTIVISION\n"
                " \n"
                "FROSTBITE BAILY BUILDS IGLOO\n"
                "GAME 1: REGULAR GAME  (LV 1)\n"
                "GAME 3: ADVANCED GAME (LV 5)\n"
                "LEVEL  PTS/BLOCK   PTS/IGLOO\n"
                "LV1    10 PTS       160 PTS\n"
                "LV2    20 PTS       320 PTS\n"
                "LV3    30 PTS       480 PTS\n"
                "LV4    40 PTS       640 PTS\n"
                "LV5    50 PTS       800 PTS\n"
                "LV6    60 PTS       960 PTS\n"
                "LV7    70 PTS      1120 PTS\n"
                "LV8    80 PTS      1280 PTS\n"
                "LV9    90 PTS      1440 PTS\n"
                "FISH ARE WORTH 200 POINTS\n"
                "IGLOO BONUS: 10*DEGREES*LEVEL\n"
                "EXTRA LIFE EVERY 5000 POINTS\n"
    },

    {"SOLSTM",  "SOLAR STORM (C)1983 IMAGIC\n"
                " \n"
                "HIT SOLAR DEBRIS TO AVOID\n"
                "PLANETARY OVERHEATING.\n"
                "WAVE ENDS WHEN YOU SHOOT ALL\n"
                "OBJECTS OR THEY REACH PLANET.\n"
                " \n"
                "SCORING:\n"
                "SUN SPOT                 5 PTS\n"
                "DELTOID/BLASTER/LANDER  10 PTS\n"
                "SOLAR FLARE             20 PTS\n"
                "SIZZLOID HIT            50 PTS\n"
                "FLEET SHIP              10 PTS\n"
                "AT END OF A WAVE WHEN SCORE IS\n"
                "500, 1000, 1500, ETC, ORBITAL\n"
                "PLATFORM APPEARS WHERE YOU CAN\n"
                "EARN BONUS POINTS + EXTRA LIFE\n"
    },    
    
   {"SPACX7",  "SPACEMASTER X7 (C)1983 20TH CF\n"
                " \n"
                "DESTROY HYPERION MILITARY BASE\n"
                " \n"
                "SCORING:\n"
                "FIREBALL            25 PTS\n"
                "HEAT SEEKER        100 PTS\n"
                "BOUNCER             50 PTS\n"
                "WANDERER           200 PTS\n"
                "HOMER              400 PTS\n"
                "BASE PER HIT        25 PTS\n"
                "BASE DESTROYED IS 1000 PTS\n"
                "FOR FIRST FOUR BASES, THEN\n"
                "2000 PTS FOR NEXT FOUR, ETC\n"
                " \n"
                "EXTRA LIFE EVERY 10,000 PTS\n"
    },    

    {"STARMA",  "STARMASTER (C)1982 ACTIVISION\n"
                "E: ENSIGN     9 ENEMIES NORMAL\n"
                "L: LEADER    17 ENEMIES FAST\n"
                "W: WING CDR  23 ENEMIES FASTER\n"
                "S: STARMASTR 31 ENEMIES FASTEST\n"
                " \n"
                "W:  ENERGY NEEDED TO WARP.\n"
                "S:  STARDATE (ELAPSED TIME).\n"
                "E:  ENERGY REMAINING.\n"
                "D:  DAMAGE CONTROL STATUS:\n"
                "    L=LASR,S=SHD,W=WARP,R=RADAR\n"
                "GREEN:  EMPTY SECTOR.\n"
                "RED:    ENEMY SECTOR.\n"
                "BLUE:   STARBASE SECTOR\n"
                "SCORE BASE(3100,4300,5700,6900)\n"
                "SCORE 100 PTS FOR EACH ENEMY\n"
                "MINUS 500 PTS STARBASE DESTROY\n"
                "MINUS 100 PTS DOCK / REPAIR\n"
                "MINUS 1   PTS PER STARDATE\n"
    },        

   {"STELTR",  "STELLAR TRACK (c)1980 SEARS\n"
                " \n"
                "DESTROY ALL ALIENS IN GALAXY\n"
                "WITH PHASERS AND PHOTONS.\n"
                " \n"
                "GAME SELECT: RANDOM MISSION\n"
                "L-DIFF:  A=PHASERS HALF STR\n"
                "R-DIFF:  A=SHIELDS HALF STR\n"
                "GALAXY MAP SHOWS NUMBER OF \n"
                "ALIENS AND STARBASES as XY\n"
                " \n"
                "PHOTON / WARP DIRECTIONS:\n"
                " \n"
                "       1     \n"
                "     8 : 2   \n"
                "    7 -o- 3  \n"
                "     6 : 4   \n"
                "       5     \n"
    },    

    {"WORMW1",  "WORM WAR I (C)1982 FOX\n"
                " \n"
                "BLAST WORMS AND BLOCKS\n"
                "AND KEEP AN EYE ON FUEL.\n"
                " \n"
                "OPT 1:  OBSTACLE COURSE\n"
                "OPT 2:  STRAIGHTAWAY COURSE\n"
                "OPT 3:  INVISIBLE WORMS\n"
                "L-DIFF: A=RANDOM WORM MOVE\n"
                "R-DIFF: A=SLOWER BRAKES\n"
                " \n"
                "WORMS ATTACK IN GROUPS AND\n"
                "BLOCKS ARE WORTH 5 PTS\n"
    },    
    
    {"SOLARF",  "SOLAR FOX (C)1982 CBS\n"
                " \n"
                "L-DIFF: A=FAST CRUISE\n"
                " \n"
                "EVERY 5 RACKS YOU GET\n"
                "A CHALLENGE RACK.\n"
                " \n"
                "SCORING\n"
                "RACKS 1 TO 5        100 PTS\n"
                "RACKS 6 TO 10       200 PTS\n"
                "RACKS 11 TO 15      300 PTS\n"
                "RACKS 16 TO 20      400 PTS\n"
                " \n"
                "CHALLENGE RACK: NUMBER OF CELLS\n"
                "  IN RACK * CELL POINT VALUE.\n"
    },    
    
    {"SKIING",  "SKIING (C)1982 ACTIVISION\n"
                " \n"
                "SLALOM RUNS\n"
                "GM1:  20 GATES, NOVICE RUN\n"
                "GM2:  40 GATES, INTERMEDIATE\n"
                "GM3:  30 GATES, EXPERT RUN\n"
                "GM4:  50 GATES, OLYMPIC RUN\n"
                "GM5:  30 GATES, RANDOM COURSE\n"
                " \n"
                "DOWNHILL RUNS\n"
                "GM6:  200 METERS, NOVICE HILL\n"
                "GM7:  300 METERS, INTERMEDIATE\n"
                "GM8:  500 METERS, EXPERT HILL\n"
                "GM9:  900 METERS, OLYMPIC HILL\n"
                "GM10: 900 METERS, RANDOM COURSE\n"
                " \n"
    },    
    
    {"ROTANK",  "ROBOT TANK (C)1982 ACTIVISION\n"
                " \n"
                "DESTROY ENEMY TANKS AND AVOID\n"
                "THEIR FIRE.\n"
                " \n"
                "A SMALL TANK APPEARS AT THE TOP\n"
                "OF YOUR SCREEN FOR EACH ENEMY\n"
                "ROBOT TANK YOU DESTROY. A SQUARE\n"
                "WITH THE NUMBER 12 APPEARS AT\n"
                "THE TOP OF YOUR SCREEN EACH TIME\n"
                "A SQUADRON OF TWELVE ARE KILLED.\n"
                " \n"
                "R = RADAR   DAMAGE\n"
                "T = TRED    DAMAGE\n"
                "V = VIDEO   DAMAGE\n"
                "C = CANNONS DAMAGE\n"
    },    
    
    {"PLAPAT",  "PLANET PATROL (C)1982 SPECTRAV\n"
                " \n"
                "PATROL PLANET DAY AND NIGHT.\n"
                "REFUEL AS NEEDED TO SURVIVE.\n"
                " \n"
                "DESTROY 3 DEPOTS TO ADVANCE\n"
                "TO DODGE AND AVOID ENEMIES.\n"
                " \n"
                "GAME 1:  SLOW GAME\n"
                "GAME 3:  FAST GAME\n"
    },    
    
    {"UCHAOS",  "UNIVERSAL CHAOS (C)1989 TELEGMS\n"
                " \n"
                "PILOT YOUR BATTLE COUP THROUGH\n"
                "THE STREETS OF PHENIX. USE THE\n"
                "JOYSTICK TO CONTROL SPEED AND\n"
                "THE FIRE BUTTON TO ELIMINATE\n"
                "INVADING MORTII SPACECRAFT.\n"
                " \n"
                "BONUS AFTER EVERY CLEARED WAVE.\n"
    },    
    
    {"MI3000",  "MISSION 3000AD (C)1983 BIT-CORP\n"
                " \n"
                "COLOR SHOWER:\n"
                "GREEN:     NORMAL\n"
                "BLUE:      FAST\n"
                "RED:       FASTEST\n"
                " \n"
                "STARBASE COLORS:\n"
                "GREY:      1+4 ARRANGEMENT\n"
                "YELLOW:    2+5 ARRANGEMENT\n"
                "ORANGE:    3+6 ARRANGEMENT\n"
                " \n"
                "DEFEAT STARFIGHTER:  100PTS\n"
                "DESTROY STARBASE:    500PTS\n"
                " \n"
                "EXTRA LIFE AFTER 6 STARBASES\n"
    },    
    
    {"OINK!!",  "OINK! (C)1982 ACTIVISION\n"
                " \n"
                "HELP PIGS PATCH THEIR HOUSE.\n"
                "L-DIFF: A=PIG DROPS AT WALL\n"
                " \n"
                "SCORE 4 POINTS FOR DROPPING\n"
                "BRICK INTO FIRST WALL, 8 PTS\n"
                "FOR DROPPING INTO SECOND WALL,\n"
                "ETC. EACH ROW IS WORTH MORE.\n"
    },    
    
   
    {"FROSTY",  "STAY FROSTY (C)2008 SPICEWARE\n"
                " \n"
                "PUT OUT ALL THE FIRES ON EACH\n"
                "LEVEL AND TAKE CARE THAT YOU\n"
                "DONT MELT DUE TO FIRE OR SUN!\n"
                "STAY FROSTY...!\n"
                " \n"
                "SCORING:\n"
                "SHRINK FIRE:           50 PTS\n"
                "EXTINGUISH FIRE:      100 PTS\n"
                "ICE:  4-10 PTS DEPEND ON SIZE\n"
                "LEVEL BONUS 1000 FOR SOLID\n"
                "SNOWMAN, 500-100 FOR VARIOUS\n"
                "MELTED STAGES.\n"
    },    
    

    {"M.A.D.",  "M.A.D. (c)1982 US GAMES\n"
                " \n"
                "Photon Cannon has 7 shot angles\n"
                " \n"
                "Computer will lock onto missile.\n"
                "It turns white before falling.\n"
                " \n"
                "Scoring:\n"
                "Each missile shot down by your\n"
                "Cannon in waves 1-6  = 100 PTS\n"
                "        After wave 6 = 200 PTS\n"
    },    
   
    {"LOCKNC",  "LOCK N CHASE (c)1982 M-NETWORK\n"
                " \n"
                "You have five thieves who enter\n"
                "vault one at a time to loot!\n"
                " \n"
                "Press button to slam doors.\n"
                " \n"
                "L-DIFF:  A = FAST GAME\n"
                " \n"
                "SCORING:\n"
                "Gold Bars  20 PTS\n"
                "Upper Trs  500,1000,2000,4000\n"
                "Lower Trs  250,500,1000, etc\n"
                "Trap a Cop 2000 points each\n"
    },    
    
    
  {"CNEXAR",  "CHALLENGE OF NEXAR 1982 SPECVSN\n"
                " \n"
                "AT each of 99 levels, DESTROY\n"
                "3 BEACONS and avoid collisions.\n"
                " \n"
                "L-DIFF:  B=5,  A=3 SHIELDS\n"
                "R-DIFF:  A=LOSE SHIELD ON TIME\n"
                "GAME 1: PRACTICE\n"
                "GAME 2: ADVANCE PRACTICE\n"
                "GAME 3: THE CHALLENGE OF NEXAR\n"
                "SPD: 1  2  3   4   5   6   7   \n"
                "PTS: 25 50 100 200 400 800 1200\n"
                "BONUS SHIELD EVERY 10K PTS\n"
                "RATING:\n"
                "  0K -  30K CADET\n"
                " 30K - 100K ADVANCED CADET\n"
                "100K - 300K STAR WARRIOR\n"
                "300K - 700K SPECTRA WARRIOR\n"
                "700K - 999K LEGION OF CHOSEN\n"
    },    

    {"DOKONG",  "DONKEY KONG 1982 NINTENDO\n"
                " \n"
                "ONLY 2 STAGES - SAVE PRINCESS\n"
                "AND REMOVE ALL RIVETS.\n"
                " \n"
                "Each screen has a score/bonus\n"
                "counter at the top when you\n"
                "clear a level.\n"
                " \n"
                "SCORING:\n"
                "Jumping a barrel     100 PTS\n"
                "Removing a rivet     100 PTS\n"
                "Smashing barrel      800 PTS\n"
    },        
    {"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",  (char*)0},
};

char inst_text[1024];
void dsShowScreenInstructions(void)
{
  short int idx=0;
  char bFound=0;
    
  decompress(bgInstructionsTiles, bgGetGfxPtr(bg0b), LZ77Vram);
  decompress(bgInstructionsMap, (void*) bgGetMapPtr(bg0b), LZ77Vram);
  dmaCopy((void *) bgInstructionsPal,(u16*) BG_PALETTE_SUB,256*2);
  unsigned short dmaVal = *(bgGetMapPtr(bg1b) +31*32);
  dmaFillWords(dmaVal | (dmaVal<<16),(void*) bgGetMapPtr(bg1b),32*24*2);
  swiWaitForVBlank();
    
  while (instructions[idx].text != (char*)0)
  {
    if (instructions[idx].gameID == myCartInfo.gameID)
    {
        bFound = 1;
        strcpy(inst_text, instructions[idx].text);
        break;
    }
    idx++;
  }
    
  if (bFound)
  {
       short line=3;
       char *token = NULL;
       token = strtok(inst_text, "\n");
       while( token != NULL ) 
       {
          dsPrintValue(1,line++,0, token);
          token = strtok(NULL, "\n");
       }
  }
  else
  {
      dsPrintValue(1,4,0, (char *)"Game Manual Not Found");
      dsPrintValue(1,5,0, (char *)"Many more comming soon!");
  }
}
